spring:
  jackson:
    #return json data non null
    default-property-inclusion: non_null

  thymeleaf:
    #缓冲的配置
    cache: false
    check-template: true
    check-template-location: true
    #开启MVC thymeleaf 视图解析
    enabled: true
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    #静态文件目标
    dest-path: ~/deploy3H

  profiles:
    active: dubbo
  application:
    name: course-selection-api

server:
  port: 9501